export const ADD_LYRICS_FOR_SONG = 'ADD_LYRICS_FOR_SONG';

export const LYRICS_ADDED_FOR_SONG = 'LYRICS_ADDED_FOR_SONG';

export const TRANSLATE_SONG_LYRICS = 'TRANSLATE_SONG_LYRICS';

export const SONG_LYRICS_TRANSLATED = 'SONG_LYRICS_TRANSLATED';
