export const CREATE_DIGITAL_TEXT = 'CREATE_DIGITAL_TEXT';

export const DIGITAL_TEXT_CREATED = 'DIGITAL_TEXT_CREATED';

export const ADD_PAGE_TO_DIGITAL_TEXT = 'ADD_PAGE_TO_DIGITAL_TEXT';

export const PAGE_ADDED_TO_DIGITAL_TEXT = 'PAGE_ADDED_TO_DIGITAL_TEXT';
